name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
dependencies:
  - python==3.9.5
  - pip==21.3.1
  - pip:
    - jupyter==1.0.0
    - nb_black==1.0.7
    - papermill==2.3.3
    - numpy==1.22.1
    - pandas==1.3.5
    - matplotlib==3.5.1
    - seaborn==0.11.2
    - pymysql==1.0.2
    - python-dotenv==0.19.2
    - sqlalchemy==1.4.28
    - pyarrow==6.0.1
    - fastparquet==0.7.2
