name: CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  precommit-lint-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - run: pip install tox
    - run: make precommit
  tests:
    runs-on: ubuntu-latest
    needs: precommit-lint-checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - run: pip install tox
    - run: make test clean-tests
  build:
    runs-on: ubuntu-latest
    needs: precommit-lint-checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - run: pip install tox
    - run: make build
